### ISSUE TITLE
Trained models

### ISSUE THREAD

**Issue by suvojit-0x55aa** [zwx8981/DBCNN-PyTorch#11]
Good work,Thanks for sharing!!! 
I was wondering if there are any available trained models on Live IQA dataset. I would appreciate if you share these ones for public access.

Kindly,
SManna

**Comment by zwx8981** [comment]
@suvojit-0x55aa Hi, I didn't save previous trained models so I can't release any model now. It's very straightforward to train models by yourself following the instruction on the ReadMe. Thank you.
