### ISSUE TITLE
LIVE数据crop到432*432，如何映射到全图

### ISSUE THREAD

**Issue by shenguquanxin** [zwx8981/DBCNN-PyTorch#12]
您好，我有几个问题请教：
1、LIVE数据集crop_size=432，那么训练出来的模型，只是针对432*432的图片而言的。但是在计算PLCC和SROCC的时候，也是432*432，那么这个PLCC只是当LIVE数据集crop_size=432时的PLCC、SROCC而不是原图的PLCC、SROCC。如果要得到真正LIVE数据集上的PLCC，需要输入原图获得预测质量，再去计算。是这样吗？
2、如1所述，LIVE的数据集训练出来的模型是针对432*432的图像输入。那么用这个模型，去预测任意尺寸的图像质量，这里有没有一个合理的说法？
3、可否提供一版自建数据集的训练代码
感谢分享，会持续关注您的工作~

**Comment by zwx8981** [comment]
@shenguquanxin 
1, 由于LIVE数据集图片尺寸大小不一，而训练时必须统一尺寸，所以只能crop，432是根据Live数据集中图片的最短边选取的。在测试的时候，是直接输入全图尺寸，不需要crop和缩放等操作。
2，理想情况肯定是训练和测试尺寸一致，但原因如上所述。
3，SCNN.py就是用于训练自建数据集进行失真分类的代码。

**Comment by shenguquanxin** [comment]
> @shenguquanxin
> 1, 由于LIVE数据集图片尺寸大小不一，而训练时必须统一尺寸，所以只能crop，432是根据Live数据集中图片的最短边选取的。在测试的时候，是直接输入全图尺寸，不需要crop和缩放等操作。
> 2，理想情况肯定是训练和测试尺寸一致，但原因如上所述。
> 3，SCNN.py就是用于训练自建数据集进行失真分类的代码。
======================================================
感谢~
SCNN部分我觉得rank的数据集已经很大了，不需要重新训练。我想的在自己数据集上训练DBCNN，而不是LIVE数据集上的DNCNN。比如只做1080P图片的评价，训练和测试都是1080P，我觉得这样应该会比较准确。
所以我请求的是在自建数据集上面训练DBCNN的代码，不知道您有没有做过这样的实验，有的话，能否share一下代码。

**Comment by zwx8981** [comment]
@shenguquanxin dbcnn本身的代码不需要改，主要是根据你的数据集修改dataloader
