### ISSUE TITLE
KADIS数据集以及S-CNN模型

### ISSUE THREAD

**Issue by shenguquanxin** [zwx8981/DBCNN-PyTorch#13]
您好，看到您的更新。目前应该是把Waterloo、VOC的合成失真数据，换成了KADIS-700k合成失真数据集。能否提供数据集的下载链接，以及基于此数据集的预训练S-CNN模型。
非常感谢~

**Comment by zwx8981** [comment]
> 您好，看到您的更新。目前应该是把Waterloo、VOC的合成失真数据，换成了KADIS-700k合成失真数据集。能否提供数据集的下载链接，以及基于此数据集的预训练S-CNN模型。
> 非常感谢~

数据集链接：http://database.mmsp-kn.de/kadid-10k-database.html
目前还没有训练好的模型，只是先更新一个代码

**Comment by shenguquanxin** [comment]
> > 您好，看到您的更新。目前应该是把Waterloo、VOC的合成失真数据，换成了KADIS-700k合成失真数据集。能否提供数据集的下载链接，以及基于此数据集的预训练S-CNN模型。
> > 非常感谢~
> 
> 数据集链接：http://database.mmsp-kn.de/kadid-10k-database.html
> 目前还没有训练好的模型，只是先更新一个代码

好，我下载一下，然后用您新更新的scnn中resnet34训练结果~~感谢~
