### ISSUE TITLE
What is the classification accuracy of SCNN?

### ISSUE THREAD

**Issue by qibao77** [zwx8981/DBCNN-PyTorch#18]
Can you provide the classification accuracy of SCNN, thank you！

**Comment by zwx8981** [comment]
@qibao77  Hi, sorry for the late reply. We didn't record the accuracy results, but in my pression, you should be able to get a classification accuracy higher than 98%. Thanks.

**Comment by vegetable09** [comment]
Appreicate for sharing your great work first!
But I really wonder where can I found the SCNN labels. In the paper, you said there are 125 labels, and in the matlab distortion dir, there is 8 kinds of distortion and each has 5 levels. so there is 40 lables? correct me if i am wrong

**Comment by zwx8981** [comment]
@vegetable09 Hi, there are only 39 classess. 7 types with 5 levels and 2 types with 2 levels.

**Comment by vegetable09** [comment]
@zwx8981 哇，谢谢大佬在线回复。
项目的scnn_bn.pth和scnn.pth对应的是SCNN.py
那 SCNN3.py 这个文件怎么是125class。

**Comment by zwx8981** [comment]
@vegetable09  SCNN3.py是给新的KADIS数据库准备的，只是先放在这，还没有实际训练

**Comment by vegetable09** [comment]
好嘞~！对啦，39个分类的位置，就是比如scnn输出39个向量，然后第八个向量值最大，然后我怎么知道这个对应的是哪一种distortion呀

**Comment by zwx8981** [comment]
这个取决于你的标签具体是怎么对应的，在分类时会把所有类别按照1-39编个号，比如你把Gaussian blur的level 3记为8，那么这个位置对应的就是Gaussian blur的level 3

**Comment by vegetable09** [comment]
如果我用的就是预训练模型呢，预训练的时候，你的标签是怎么对应的呀

**Comment by vegetable09** [comment]
我想直接用你的SCNN来判断GAN退化低质量图像的多样性，谢谢啦

**Comment by zwx8981** [comment]
https://github.com/zwx8981/DBCNN/blob/master/distortion_generator/distortion_generator.m 可以参照这个，应该是这个顺序

**Comment by vegetable09** [comment]
对，这个我看到了，确认一下顺序哈：

**Comment by vegetable09** [comment]
好的！结合论文图2，我知道了，谢谢！
