### ISSUE TITLE
some size of image  got error

### ISSUE THREAD

**Issue by clearlovewl** [zwx8981/DBCNN-PyTorch#2]
such as torch.Size([1, 3, 764, 960])
got
`  File "DBCNN.py", line 89, in forward
    X2 = X2.view(N, 128, H*W)
RuntimeError: shape '[1, 128, 2820]' is invalid for input of size 368640`
is that means i just can use square image to test？

**Comment by clearlovewl** [comment]
this line `if H != H2 | W != W2:`  change to  `if (H != H2) | (W != W2):` will solve the problem

**Comment by zwx8981** [comment]
@clearlovewl  Thank you! I will fix this issue.
