### ISSUE TITLE
How to do the individual distortion test?

### ISSUE THREAD

**Issue by lllllllllllll-llll** [zwx8981/DBCNN-PyTorch#20]
论文的table 2，table 3和table 4的individual distortion types是怎么做的实验啊？比如说像table 2测live数据集的时候，是不是先把model在整个live上进行和table 1一样的分80%和20%的训练测试，然后保存model后对这5个失真类型的所有图片进行SROCC的打分呢？这部不是很清楚，请教一下，谢谢！

**Comment by zwx8981** [comment]
@lllllllllllll-llll 你好，你的理解没问题，就是这么做的，individual distortion type和all type的训练都是一样的，只是改变了测试集而已。

**Comment by lllllllllllll-llll** [comment]
谢谢回复，那万一我们做individual distortion type的时候里面的图片和我们训练model的时候有重复的话怎么办呢，结果不是会高一点吗？

**Comment by zwx8981** [comment]
不会有重复的，因为训练和测试集的划分也是一样的，相当于把分好的all type的test set中每个type单独拿出来算一下srcc/plcc结果。

**Comment by lllllllllllll-llll** [comment]
啊，是这样啊，懂了。意思就是做individual distortion type的时候是拿的当时我们训练测试model里面的20%测试集里面的独立失真类型吧，那大概每个失真类型只有大概32张左右吧，是这样吗？谢谢

**Comment by zwx8981** [comment]
是的

**Comment by lllllllllllll-llll** [comment]
谢谢您，还有个问题就是做跨数据集的时候srocc正负值的问题怎么解决呢？比如：拿live上训练好的model，在整个csiq测试，live上的label是dmos，而csiq是mos，我拿您的model测了一下，srocc结果是负的，这时候符号就需要丢弃吧。

**Comment by zwx8981** [comment]
对，当两个database的标签单调性不一致时（一个mos一个dmos），对结果取绝对值就行

**Comment by lllllllllllll-llll** [comment]
谢谢，懂了！
