### ISSUE TITLE
您好，请问一下cross database的问题

### ISSUE THREAD

**Issue by lllllllllllll-llll** [zwx8981/DBCNN-PyTorch#21]
文章里面的cross database部分写的是"All experiments are conduct by training models on one entir database and test them on th other databases"，那么如何做呢？意思是在live上分80%训练，20%测试的model直接在整个csiq，tid2013或者livec上面测试吗？还是应该用其他方法呢？

**Comment by zwx8981** [comment]
cross database不分训练测试，比如在live全部图像上训练，并在其他库的全部图像上测试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Xs <notifications@github.com&gt;
发送时间: 2021年2月28日 20:17
收件人: zwx8981/DBCNN-PyTorch <DBCNN-PyTorch@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[zwx8981/DBCNN-PyTorch] 您好，请问一下cross database的问题 (#21)

**Comment by lllllllllllll-llll** [comment]
谢谢解答，那意思就是在原本的训练测试阶段，直接把训练集用作整个LIVE数据集，然后测试集用整个csiq或者livec吗

**Comment by zwx8981** [comment]
是的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Xs <notifications@github.com&gt;
发送时间: 2021年2月28日 20:24
收件人: zwx8981/DBCNN-PyTorch <DBCNN-PyTorch@noreply.github.com&gt;
抄送: Onionbao <411965697@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[zwx8981/DBCNN-PyTorch] 您好，请问一下cross database的问题 (#21)





 
谢谢解答，那意思就是在原本的训练测试阶段，直接把训练集用作整个LIVE数据集，然后测试集用整个csiq或者livec吗

**Comment by lllllllllllll-llll** [comment]
谢谢
