### ISSUE TITLE
Train scnn.py

### ISSUE THREAD

**Issue by Nirvana-feng** [zwx8981/DBCNN-PyTorch#27]
Hello author, I want to train scnn.py. But the model I needed for training is not there. How do I get this model?
![image](https://user-images.githubusercontent.com/67857885/144811525-8f400534-a6e1-4ecf-8f4f-f1dc196e9a36.png)

**Comment by zwx8981** [comment]
This is the path where your trained model will be saved. Change this line to your local path.

**Comment by Nirvana-feng** [comment]
The model is saved through matlab training. It seems that two models are saved in pytorch.
![image](https://user-images.githubusercontent.com/67857885/144823441-52840cbd-3a87-4703-a672-4b972405020c.png)

**Comment by zwx8981** [comment]
Yes, this project is purely based on PyTorch. It seems that you have trained the entire DBCNN model. To train the SCNN, you don't need the model trained by matlab. The only thing you should work with Matlab is to generate distorted images.

**Comment by Nirvana-feng** [comment]
Yes, I have trained DBCNN model. Now I want to train SCNN, but I don't know the specific model path.

**Comment by zwx8981** [comment]
This is the path that your trained SCNN model will be saved, not a path to a starting model. You can directly start training and the SCNN checkpoint will be saved in this path.

**Comment by Nirvana-feng** [comment]
I understand what you said, but when training the SCNN model, isn't the training file scnn.py? I think there is a path in this file
![image](https://user-images.githubusercontent.com/67857885/144840281-eda0fb05-79ae-4a0a-8c27-3d81cc37744d.png)

**Comment by Nirvana-feng** [comment]
Sorry, I seem to understand what you mean. I'll do it myself

**Comment by Nirvana-feng** [comment]
thank you,my code has run
