### ISSUE TITLE
How can we predict score of image quality using DBCNN model ? 

### ISSUE THREAD

**Issue by sudsfsp** [zwx8981/DBCNN-PyTorch#4]
I had run successfully  model and got FC model DB model. How can we utilized these models to predict score?

**Comment by zwx8981** [comment]
@sudsfsp Hi, given an input image, the output of the last layer of DBCNN is the predicted quality score.

**Comment by sudsfsp** [comment]
> @sudsfsp Hi, given an input image, the output of the last layer of DBCNN is the predicted quality score.

@zwx8981 .. Sorry I am a new in pytorch. In DBCNN.py .. image are divided into two parts train and test but i want to pass only one image and check score. Can you write a little code for me who help to check score for one image.

**Comment by zwx8981** [comment]
@sudsfsp Hi, I have uploaded a simple_demo.py file，you can use it to predict the score of an image after setting paths to your models.

**Comment by sudsfsp** [comment]
> @sudsfsp Hi, I have uploaded a simple_demo.py file，you can use it to predict the score of an image after setting paths to your models.

@zwx8981 Thank you so much. Actually i got a below error 

 model.load_state_dict(checkpoint['state_dict'])
KeyError: 'state_dict'

I retrained SCNN.py so i got net_params25.pkl  best model though SCNN training.  So i putted net_params25.pkl in SCNN route path (simple_demo.py) and after run DBCNN.py i got two model in two different folder (fc_models and db_models). So i selected fc_model (net_param_best.pkl) folder for second path (checkpoint path), am i correct or wrong ?

**Comment by zwx8981** [comment]
@sudsfsp  This may be a typo, try to change the model.load_state_dict(checkpoint['state_dict']) to model.load_state_dict(checkpoint) and run again.

**Comment by sudsfsp** [comment]
> @sudsfsp This may be a typo, try to change the model.load_state_dict(checkpoint['state_dict']) to model.load_state_dict(checkpoint) and run again.

@zwx8981 ... A lot of thanks.. Its running. :)
