### ISSUE TITLE
Is dmos_realigned.mat different from dmos.mat?

### ISSUE THREAD

**Issue by witwitchayakarn** [zwx8981/DBCNN-PyTorch#6]
Thank you so much for you code.

I'm curious that in Class LIVEFolder, you refer to 'dmos_realigned.mat' under Live dataset databaserelease2 but I found only 'dmos.mat' under the folder. Is it the same file or is there any additional process?
Thank you.

**Comment by zwx8981** [comment]
@witwitchayakarn Hi, you may get the dmos_realigned.mat from http://live.ece.utexas.edu/research/Quality/subjective.htm. The link may no be so obvious, it locates in the context of the webpage as:

Download Release 2

Subjective database Release 2 .

Please fill THIS form and the password will be sent to you.

If you download the database, it is assumed that you agree to the copyright notice

Update to Release 2

Download realigned subjective quality data **here** . This data was obtained by running realignment experiments on Release 2 data. The details of the experiment can be found in the paper.

**Comment by witwitchayakarn** [comment]
I got it. Thanks a lot.
