### ISSUE TITLE
算法请教

### ISSUE THREAD

**Issue by gxdi** [zwx8981/DBCNN-PyTorch#9]
您好，我使用您的代码在pytorch环境下运行DBCNN.py进行学习时，有一个报错 
y = torch.tensor(y.cuda(async=True))
                                             ^
SyntaxError: invalid syntax
具体位置在DBCNN.py的第204及246行，期待得到您的回答！！

**Comment by zwx8981** [comment]
@gxdi 你好，请问你的pytorch版本是多少呢？可以去掉y.cuda()里的async=True试试。
